[workspace]
resolver = "2"
members = [
    "crates/wasm-bin",
    "crates/wasm-text",
    "programs/add",
    "programs/box",
    "programs/hello",
    "programs/log",
]

[profile.release]
lto = "fat"
opt-level = "s"
