version: '3'

tasks:
  build-wasm:
    vars:
      OUT_PATH: "./target/wasm32-unknown-unknown/wasm/examples"

    cmds:
      - cargo build --profile wasm --examples --target wasm32-unknown-unknown
      - ls -l {{ .OUT_PATH }}
